# Generated by Django 2.2.7 on 2019-11-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191120_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=225)),
                ('event_title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('seats', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('hours_needed', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Location')),
                ('tags', models.ManyToManyField(to='events.Tag')),
            ],
        ),
    ]
