# Generated by Django 2.2.7 on 2019-11-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineitem',
            old_name='events',
            new_name='event',
        ),
    ]
